I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 11, in script call
    call chap1
  File "game/chap1.rpy", line 77, in script
    fe "Morning Melyssa!"
Exception: Sayer 'fe' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 11, in script call
    call chap1
  File "game/chap1.rpy", line 77, in script
    fe "Morning Melyssa!"
  File "C:\Users\GGPC\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\GGPC\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'fe' is not defined.

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
Project Bismuth 1.0
Mon Jan 23 23:59:35 2023
